# Generated by Django 3.1.7 on 2021-03-29 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_user_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='listing',
            new_name='watching',
        ),
    ]
